from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterable, Iterator, Sequence


DEFAULT_SQLITE_PATH = Path("results/paper_trading.db")
POSTGRES_SCHEMES = ("postgresql://", "postgres://")
RISK_GUARD_SETTING_KEY = "portfolio_risk_guard_enabled"


def resolve_database_target(
    explicit: str | Path | None = None,
) -> str | Path:
    """Resolve an explicit target, Replit PostgreSQL, or the local SQLite file."""
    if explicit is not None:
        return explicit
    database_url = (
        os.getenv("SONIC_DATABASE_URL", "").strip()
        or os.getenv("DATABASE_URL", "").strip()
    )
    if database_url:
        return database_url
    return Path(os.getenv("SONIC_DB_PATH", str(DEFAULT_SQLITE_PATH)))


def is_postgres_target(target: str | Path) -> bool:
    return isinstance(target, str) and target.lower().startswith(
        POSTGRES_SCHEMES
    )


def _postgres_sql(sql: str) -> str:
    # Project queries use DB-API positional placeholders and do not contain
    # literal question marks. psycopg uses %s for the same parameter style.
    return sql.replace("?", "%s")


class DatabaseConnection:
    """Small DB-API compatibility layer used by the scanner and API.

    It intentionally exposes only the operations this project needs. SQL
    remains parameterized while SQLite and psycopg placeholder differences are
    handled in one place.
    """

    def __init__(self, raw: Any, dialect: str):
        self.raw = raw
        self.dialect = dialect

    def execute(
        self, sql: str, parameters: Sequence[Any] | None = None
    ):
        statement = _postgres_sql(sql) if self.dialect == "postgresql" else sql
        return self.raw.execute(statement, parameters or ())

    def executemany(
        self, sql: str, parameters: Iterable[Sequence[Any]]
    ):
        statement = _postgres_sql(sql) if self.dialect == "postgresql" else sql
        if self.dialect == "postgresql":
            cursor = self.raw.cursor()
            cursor.executemany(statement, parameters)
            return cursor
        return self.raw.executemany(statement, parameters)

    def commit(self) -> None:
        self.raw.commit()

    def rollback(self) -> None:
        self.raw.rollback()

    def close(self) -> None:
        self.raw.close()

    @contextmanager
    def transaction(self) -> Iterator["DatabaseConnection"]:
        try:
            yield self
        except BaseException:
            self.rollback()
            raise
        else:
            self.commit()

    def __enter__(self) -> "DatabaseConnection":
        return self

    def __exit__(self, exc_type, exc, _traceback) -> bool:
        try:
            if exc_type is None:
                self.commit()
            else:
                self.rollback()
        finally:
            self.close()
        return False


def scalar(cursor) -> Any:
    row = cursor.fetchone()
    if row is None:
        return None
    if isinstance(row, dict):
        return next(iter(row.values()))
    return row[0]


def _connect_raw(target: str | Path) -> DatabaseConnection:
    if is_postgres_target(target):
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:  # pragma: no cover - configuration failure
            raise RuntimeError(
                "PostgreSQL requires psycopg. Run `pip install -r requirements.txt`."
            ) from exc
        raw = psycopg.connect(str(target), row_factory=dict_row)
        return DatabaseConnection(raw, "postgresql")

    path = Path(target)
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = sqlite3.connect(path, timeout=30)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA journal_mode=WAL")
    raw.execute("PRAGMA foreign_keys=ON")
    return DatabaseConnection(raw, "sqlite")


def _table_columns(connection: DatabaseConnection, table: str) -> set[str]:
    if connection.dialect == "postgresql":
        rows = connection.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = current_schema() AND table_name = ?
            """,
            (table,),
        ).fetchall()
        return {row["column_name"] for row in rows}
    return {
        row[1]
        for row in connection.execute(f"PRAGMA table_info({table})").fetchall()
    }


def initialize_schema(connection: DatabaseConnection) -> None:
    identity = (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY"
        if connection.dialect == "postgresql"
        else "INTEGER"
    )
    statements = [
        f"""
        CREATE TABLE IF NOT EXISTS scan_runs (
            id {identity} PRIMARY KEY,
            scanned_at TEXT NOT NULL,
            universe_count INTEGER NOT NULL,
            success_count INTEGER NOT NULL,
            long_ready INTEGER NOT NULL,
            short_ready INTEGER NOT NULL,
            wait_count INTEGER NOT NULL,
            error_count INTEGER NOT NULL,
            duration_seconds DOUBLE PRECISION NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS latest_setups (
            rank INTEGER, name TEXT, symbol TEXT, base TEXT, side TEXT,
            status TEXT, actionable INTEGER, signal_time TEXT,
            bar_open DOUBLE PRECISION, bar_high DOUBLE PRECISION,
            bar_low DOUBLE PRECISION, bar_close DOUBLE PRECISION,
            entry DOUBLE PRECISION, sl DOUBLE PRECISION,
            tp1 DOUBLE PRECISION, tp2 DOUBLE PRECISION,
            tp1_rr DOUBLE PRECISION, tp2_rr DOUBLE PRECISION,
            trail_h1 DOUBLE PRECISION, pa TEXT, missing TEXT,
            f_trend INTEGER, f_regime INTEGER, f_session INTEGER,
            f_breakout INTEGER, f_dow INTEGER, f_value_zone INTEGER,
            f_pa INTEGER, session TEXT, adx DOUBLE PRECISION,
            separation DOUBLE PRECISION, ema200_aligned INTEGER,
            pva_state TEXT, pva_ratio DOUBLE PRECISION,
            pva_rising INTEGER, pva_climax INTEGER, entry_model TEXT,
            contract_size DOUBLE PRECISION, amount_step DOUBLE PRECISION,
            min_contracts DOUBLE PRECISION,
            PRIMARY KEY (symbol, side)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS paper_trades (
            id {identity} PRIMARY KEY,
            signal_key TEXT NOT NULL UNIQUE,
            symbol TEXT NOT NULL, base TEXT, name TEXT, side TEXT NOT NULL,
            status TEXT NOT NULL, opened_at TEXT NOT NULL,
            entry DOUBLE PRECISION NOT NULL,
            initial_sl DOUBLE PRECISION NOT NULL,
            current_sl DOUBLE PRECISION NOT NULL,
            tp1 DOUBLE PRECISION NOT NULL, tp2 DOUBLE PRECISION NOT NULL,
            tp1_rr DOUBLE PRECISION NOT NULL, tp2_rr DOUBLE PRECISION NOT NULL,
            trail_h1 DOUBLE PRECISION,
            risk DOUBLE PRECISION NOT NULL,
            remaining DOUBLE PRECISION NOT NULL DEFAULT 1,
            realized_r DOUBLE PRECISION NOT NULL DEFAULT 0,
            tp1_hit INTEGER NOT NULL DEFAULT 0,
            tp2_hit INTEGER NOT NULL DEFAULT 0,
            last_bar_time TEXT NOT NULL,
            mfe_r DOUBLE PRECISION NOT NULL DEFAULT 0,
            mae_r DOUBLE PRECISION NOT NULL DEFAULT 0,
            risk_pct DOUBLE PRECISION NOT NULL DEFAULT 0.5,
            expires_at TEXT, filled_at TEXT, closed_at TEXT,
            exit_price DOUBLE PRECISION, exit_reason TEXT,
            total_r DOUBLE PRECISION
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS paper_events (
            id {identity} PRIMARY KEY,
            trade_id INTEGER NOT NULL,
            event_at TEXT NOT NULL, event TEXT NOT NULL,
            price DOUBLE PRECISION,
            delta_r DOUBLE PRECISION NOT NULL DEFAULT 0,
            detail TEXT,
            FOREIGN KEY (trade_id) REFERENCES paper_trades(id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS scan_lock (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            locked_at TEXT, holder TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS runtime_settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        INSERT INTO scan_lock (id, locked_at, holder)
        VALUES (1, NULL, NULL)
        ON CONFLICT (id) DO NOTHING
        """,
        """
        INSERT INTO runtime_settings (key, value)
        VALUES ('portfolio_risk_guard_enabled', 'true')
        ON CONFLICT (key) DO NOTHING
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_paper_trades_status_opened
        ON paper_trades (status, opened_at)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_paper_events_trade_event_at
        ON paper_events (trade_id, event_at)
        """,
    ]
    with connection.transaction():
        for statement in statements:
            connection.execute(statement)


def get_runtime_setting(
    connection: DatabaseConnection,
    key: str,
    default: str | None = None,
) -> str | None:
    row = connection.execute(
        "SELECT value FROM runtime_settings WHERE key=?",
        (key,),
    ).fetchone()
    return default if row is None else str(row["value"])


def set_runtime_setting(
    connection: DatabaseConnection,
    key: str,
    value: str,
) -> None:
    with connection.transaction():
        connection.execute(
            """
            INSERT INTO runtime_settings (key, value, updated_at)
            VALUES (?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT (key) DO UPDATE SET
                value=excluded.value,
                updated_at=CURRENT_TIMESTAMP
            """,
            (key, value),
        )


def portfolio_risk_guard_enabled(connection: DatabaseConnection) -> bool:
    value = get_runtime_setting(
        connection,
        RISK_GUARD_SETTING_KEY,
        "true",
    )
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def apply_legacy_migrations(
    connection: DatabaseConnection, risk_pct_per_trade: float
) -> None:
    setup_migrations = {
        "f_regime": "INTEGER",
        "f_session": "INTEGER",
        "session": "TEXT",
        "adx": "DOUBLE PRECISION",
        "separation": "DOUBLE PRECISION",
        "ema200_aligned": "INTEGER",
        "pva_state": "TEXT",
        "pva_ratio": "DOUBLE PRECISION",
        "pva_rising": "INTEGER",
        "pva_climax": "INTEGER",
        "entry_model": "TEXT",
    }
    trade_migrations = {
        "risk_pct": (
            f"DOUBLE PRECISION NOT NULL DEFAULT {float(risk_pct_per_trade)}"
        ),
        "expires_at": "TEXT",
        "filled_at": "TEXT",
    }
    with connection.transaction():
        existing = _table_columns(connection, "latest_setups")
        for column, sql_type in setup_migrations.items():
            if column not in existing:
                connection.execute(
                    f"ALTER TABLE latest_setups ADD COLUMN {column} {sql_type}"
                )

        existing = _table_columns(connection, "paper_trades")
        for column, sql_type in trade_migrations.items():
            if column not in existing:
                connection.execute(
                    f"ALTER TABLE paper_trades ADD COLUMN {column} {sql_type}"
                )

        connection.execute(
            """
            UPDATE paper_trades
            SET filled_at = (
                SELECT MIN(event_at)
                FROM paper_events
                WHERE paper_events.trade_id = paper_trades.id
                  AND paper_events.event IN ('FILL', 'OPEN')
            )
            WHERE filled_at IS NULL
              AND EXISTS (
                SELECT 1 FROM paper_events
                WHERE paper_events.trade_id = paper_trades.id
                  AND paper_events.event IN ('FILL', 'OPEN')
              )
            """
        )


def connect_database(
    target: str | Path | None = None,
    *,
    risk_pct_per_trade: float = 0.5,
    initialize: bool = True,
) -> DatabaseConnection:
    connection = _connect_raw(resolve_database_target(target))
    if initialize:
        try:
            initialize_schema(connection)
            apply_legacy_migrations(connection, risk_pct_per_trade)
        except BaseException:
            connection.close()
            raise
    return connection
